name: armv7-build

on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch_name:
          - {
              gcc_version: "8.3.0",
              toolchain: "https://sourceforge.net/projects/raspberry-pi-cross-compilers/files/Raspberry%20Pi%20GCC%20Cross-Compiler%20Toolchains/Buster/GCC%208.3.0/Raspberry%20Pi%203A%2B%2C%203B%2B%2C%204/cross-gcc-8.3.0-pi_3%2B.tar.gz",
            }
#           - {
#               gcc_version: "9.4.0",
#               toolchain: "https://sourceforge.net/projects/raspberry-pi-cross-compilers/files/Raspberry%20Pi%20GCC%20Cross-Compiler%20Toolchains/Buster/GCC%209.4.0/Raspberry%20Pi%203A%2B%2C%203B%2B%2C%204/cross-gcc-9.4.0-pi_3%2B.tar.gz",
#             }
#           - {
#               gcc_version: "10.3.0",
#               toolchain: "https://sourceforge.net/projects/raspberry-pi-cross-compilers/files/Raspberry%20Pi%20GCC%20Cross-Compiler%20Toolchains/Buster/GCC%2010.3.0/Raspberry%20Pi%203A%2B%2C%203B%2B%2C%204/cross-gcc-10.3.0-pi_3%2B.tar.gz",
#             }
    steps:
      - uses: actions/checkout@v2
      # job start
      - name: Download toolchain
        run: |
          wget -q ${{ matrix.arch_name.toolchain }}
          tar xf cross-gcc-${{ matrix.arch_name.gcc_version }}-pi_3+.tar.gz
      - name: docker build
        run: |
          docker build -f ./armv7/${{ matrix.arch_name.gcc_version }}/Dockerfile -t  wesely-armv7-${{ matrix.arch_name.gcc_version }} ./
      - name: verify
        run: |
          docker images
